### PR TITLE
Add tests for entry_points

### PR DESCRIPTION
**Pull request by mrakitin**
This PR adds tests for `intake.drivers` `entry_points`.

### CODE REVIEW

**Comment by mrakitin** [comment]
When I ran the build locally, I observed the following issues:
```py
+ intake drivers enable driver bluesky-event-stream
+ intake drivers enable driver bluesky-jsonl-catalog
Traceback (most recent call last):
  File "/opt/conda/conda-bld/databroker_1569455013708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/intake", line 6, in <module>
    from intake.cli.client.__main__ import main
  File "/opt/conda/conda-bld/databroker_1569455013708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/intake/__init__.py", line 26, in <module>
    registry.update(autodiscover())
  File "/opt/conda/conda-bld/databroker_1569455013708/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/intake/source/discovery.py", line 109, in autodiscover
    module_name, object_name = dotted_object_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Tests failed for databroker-1.0.0a5-py_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken
WARNING:conda_build.build:Tests failed for databroker-1.0.0a5-py_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken
WARNING conda_build.build:tests_failed(2230): Tests failed for databroker-1.0.0a5-py_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken
TESTS FAILED: databroker-1.0.0a5-py_1.tar.bz2
```

I also observed a similar errors when I installed it on my machine after some time of using it. @danielballan, have you encountered it?

**Comment by mrakitin** [comment]
I decided to use a lighter test to check if the bluesky drivers are enabled.

Still would like to understand what broke intake. I guess it was due to I tried to enable already enabled driver.

**Comment by danielballan** [comment]
Hm. I have not encountered that. If you can reproduce locally, can you add a `print(dotted_object_name)` so we can see what value is tripping it up?

**Comment by mrakitin** [comment]
It's easy to reproduce following the steps:
```bash
$ conda create -n databroker-feedstock-pr8 databroker python=3.7 -c nsls2forge
$ conda activate databroker-feedstock-pr8
$ intake drivers list
$ intake drivers enable driver bluesky-event-stream
$ intake drivers list
```
The print is here:
```py
$ intake drivers list
!!! ERROR in /Users/mrakitin/anaconda3/envs/databroker-feedstock-pr8/lib/python3.7/site-packages/intake/source/discovery.py, line 109: bluesky-event-stream
Traceback (most recent call last):
  File "/Users/mrakitin/anaconda3/envs/databroker-feedstock-pr8/bin/intake", line 6, in <module>
    from intake.cli.client.__main__ import main
  File "/Users/mrakitin/anaconda3/envs/databroker-feedstock-pr8/lib/python3.7/site-packages/intake/__init__.py", line 26, in <module>
    registry.update(autodiscover())
  File "/Users/mrakitin/anaconda3/envs/databroker-feedstock-pr8/lib/python3.7/site-packages/intake/source/discovery.py", line 110, in autodiscover
    module_name, object_name = dotted_object_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
produced by the following addition:
```py
        print(f'!!! ERROR in {__file__}, line 109: {dotted_object_name}')
```

**Pull request closed without merging**
